# Generated by Django 3.1.7 on 2021-09-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('year_exp', models.CharField(max_length=100)),
                ('terms', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'user_details',
            },
        ),
    ]
